name: Generate Changelog

on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
    pull_request:
        paths:
            - 'src/**'

jobs:

    generate-changelog:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Generate Changelog File
              run: |
                MERGE_COMMIT=$(git log --merges --format="%H" -1)
                git log --pretty=format:"%h - %s (%an)" $MERGE_COMMIT^..$MERGE_COMMIT > changelog.txt
                cat changelog.txt

            - name: Commit Changelog File
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add changelog.txt
                git commit -m "Add changelog for pull request"
                git push origin HEAD:main
        env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    

