name: Generate Changelog

on:
    pull_request:
        paths:
            - 'src/**'

jobs:

    generate-changelog:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Generate Changelog File
              run: |
                BASE_BRANCH=$(echo ${{ github.event.pull_request.base.ref }})
                HEAD_BRANCH=$(echo ${{ github.event.pull_request.head.ref }})
                git fetch origin $BASE_BRANCH
                git fetch origin $HEAD_BRANCH
                BASE_COMMIT=$(git rev-parse origin/$BASE_BRANCH)
                HEAD_COMMIT=$(git rev-parse origin/$HEAD_BRANCH)
                git log --pretty=format:"%h - %s (%an)" $BASE_COMMIT..$HEAD_COMMIT > changelog.txt
                cat changelog.txt

            - name: Commit Changelog File
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git pull --rebase origin ${{ github.head_ref }}
                git add changelog.txt
                git commit -m "Added changelog"
                git push origin HEAD:${{ github.head_ref }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    

