name: Test Action

on:
    pull_request:
        paths:
            - 'src/**'
            
jobs:

    test:
        runs-on: ubuntu-latest

        steps:
        - name: ACTION TEST
          run: echo "changed in src/**"